# Generated by Django 5.1.15 on 2026-09-19 17:54

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=512, upload_to=apps.documents.models.tenant_document_upload_path),
        ),
    ]
