# Generated by Django 5.1.15 on 2026-09-20 13:27

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentchunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='document_ch_organiz_ede940_idx',
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
